name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform/azure/north-europe
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/azure/north-europe
        run: terraform apply -auto-approve

      - name: Terraform Init
        working-directory: terraform/azure/west-europe
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/azure/west-europe
        run: terraform apply -auto-approve