name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: Production
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform/azure/north-europe
        run: terraform init

      - name: Terraform Apply
        id: north
        working-directory: terraform/azure/north-europe
        run: |
          terraform apply -auto-approve -var="database_password=${{ secrets.DATABASE_PASSWORD }}"
          north_europe_hostname=$(terraform output default_hostname)
          echo "north_europe_hostname=$north_europe_hostname" >> $GITHUB_OUTPUT
          north_europe_database_server_id=$(terraform output database_server_id)
          echo "north_europe_database_server_id=$north_europe_database_server_id" >> $GITHUB_OUTPUT

      - name: Terraform Init
        working-directory: terraform/azure/west-europe
        run: terraform init

      - name: Terraform Apply
        id: west
        working-directory: terraform/azure/west-europe
        run: |
          terraform apply -auto-approve -var="primary_database_server_id=${{ steps.north.outputs.north_europe_database_server_id }}" -var="database_password=${{ secrets.DATABASE_PASSWORD }}"
          west_europe_hostname=$(terraform output default_hostname)
          echo "west_europe_hostname=$west_europe_hostname" >> $GITHUB_OUTPUT

      - name: Terraform Init
        working-directory: terraform/azure/global/frontdoor
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/azure/global/frontdoor
        run: |
          terraform apply -auto-approve -var="north_europe_default_hostname=${{ steps.north.outputs.north_europe_hostname }}" -var="west_europe_default_hostname=${{ steps.west.outputs.west_europe_hostname }}"